# This is a basic workflow to help you get started with Actions

name: My-GitHubActions-Basics
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME    : "flask_deploy_ver-${{ github.sha }}"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello World from Testing Job"
      - name: Execute few commands
        run: |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Hello Message3"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: ls -la
  #Another job added
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello World from Deploy Job"
        
      - name: Deployment package
        run: echo "Deploy package name is ${{ env.PACKAGE_NAME }}"
       
